USE BookShop;
GO:
-- SELECT * from BOOK_INFORMATION;

CREATE TABLE BOOK_INFORMATION (
    BOOK_ID INT IDENTITY(1,1) PRIMARY KEY,
    TITLE VARCHAR (255) NOT NULL,
	AUTHOR VARCHAR (255) NOT NULL,
	BOOK_TYPE VARCHAR (255),
	PUBLISH_YEAR DATE,
	PUBLISHER VARCHAR (255),
	PRICE FLOAT
);

-- DELETE TABLE
DROP TABLE BOOK_INFORMATION;
DROP TABLE CUSTOMER_INFORMATION;
-- DELETE DATA ON TABLE
TRUNCATE TABLE BOOK_INFORMATION;
TRUNCATE TABLE CUSTOMER_INFORMATION;

-- INSERT DATA 
INSERT INTO BOOK_INFORMATION (TITLE, AUTHOR, PRICE)
VALUES ('CHUNG KHOAN', 'DUC', '300.2');

-- UPDATE VALUE FOR IDETITY 
SET IDENTITY_INSERT BOOK_INFORMATION ON;
DELETE FROM BOOK_INFORMATION WHERE BOOK_ID = 12;
INSERT INTO BOOK_INFORMATION (BOOK_ID, TITLE, AUTHOR,PRICE)
VALUES (12, 'CHUNG KHOAN', 'DUC', '300.2');
SET IDENTITY_INSERT BOOK_INFORMATION OFF;


-- CUSTOMER
CREATE TABLE CUSTOMER_INFORMATION (
    CUSTOMER_ID INT IDENTITY(1,1) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR (255) NOT NULL,
	CUSTOMER_USER_NAME VARCHAR (255) NOT NULL,
	CUSTOMER_PASSWORD VARCHAR (255) NOT NULL,
	SHIPPING_ADDRESS VARCHAR (255) NOT NULL,
	BILLING_ADDRESS VARCHAR (255) NOT NULL
);